## CAIS++ Logistic Regression Workshop

Before you go through this code, make sure you read [lesson 3]('http://caisplusplus.usc.edu/blog/curriculum/lesson3') from our curriculum

In [17]:
import pickle # used to save and restore python objects
import gzip
import numpy as np

# Load the dataset
f = gzip.open('mnist.pkl.gz', 'rb')
train_set, valid_set, test_set = pickle.load(f, encoding = 'latin1')
f.close()

# gather intelligence on the data
print(type(train_set))
print(type(test_set))

<class 'tuple'>
<class 'tuple'>


In [18]:
# taking a closer look at the data, and how it is formatted. 
print("Inputs:")
print(train_set[0])

## There's 50,000 MNIST images, each rerpesented as a vector of length 784 (28 x 28).
## A 0 corresponds to a dark pixel, and a 1 corresponds to a light pixel
print("Inputs shape is " + str(train_set[0].shape)) 
print("Input type is " + str(type(train_set[0])))
print("Labels:")

## There's 50,000 labels (one for each example)
print(train_set[1])
print("Labels shape is" + str(train_set[1].shape))
print("Labels type is " + str(type(train_set[1])))

Inputs:
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
Inputs shape is (50000, 784)
Input type is <class 'numpy.ndarray'>
Labels:
[5 0 4 ..., 8 4 8]
Labels shape is(50000,)
Labels type is <class 'numpy.ndarray'>


In [19]:
import numpy as np
def to_categorical(y, nb_classes):
    """ to_categorical.

    Convert class vector (integers from 0 to nb_classes)
    to binary class matrix, for use with categorical_crossentropy.

    Arguments:
        y: `array`. Class vector to convert.
        nb_classes: `int`. Total number of classes.

    """
    y = np.asarray(y, dtype='int32')
    if not nb_classes:
        nb_classes = np.max(y)+1
    Y = np.zeros((len(y), nb_classes))
    Y[np.arange(len(y)),y] = 1.
    return Y

In [20]:
train_x = train_set[0]
train_y = to_categorical(train_set[1], 10)
test_x = test_set[0]
test_y = to_categorical(test_set[1],10)

# let's see result of categorizing the outputs
print(test_y[:5])

[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]


In [28]:
## generate_batch() is pretty simple - all it really does is return a "batch" of data (MNIST images)
## An an argument, it takes in the desired batch size.
## We want to complete the "indexes = " line, where we want to randomly choose a set of images from the training set
## The size of this set should be equal to the batch_size

## A hint: use the np.random.randomint() function to intialize the "indexes" variable.
## Now you can see we are just returning the images from train_x that correspond to the indexes

def generate_batch(batch_size):
    
    return train_x[indexes], train_y[indexes]

In [22]:
import tensorflow as tf
# this just helps with using tensorflow inside jupyter
# (basically, resets/clears all the tensorflow variables)
tf.reset_default_graph()

In [23]:
# Creating and initializing tensorflow graph placeholders and variables.
# W, and b (our weights and biases, have been declared for you already):

W = tf.get_variable("W", shape=[784, 10], initializer = tf.contrib.layers.xavier_initializer())

b = tf.Variable(tf.zeros([10]))

## Now, create a Tenserflow placeholder for x, and y_ 
## More info here: https://www.tensorflow.org/versions/r1.1/get_started/mnist/beginners
## (y_ is a placeholder for the correct answers (the one-hot vector with digit labels))



<img src="https://www.tensorflow.org/versions/r1.1/images/softmax-regression-scalargraph.png" style="width: 600px;"/>
<br />
<br />
<img src="https://www.tensorflow.org/versions/r1.1/images/softmax-regression-vectorequation.png" style="width: 600px;"/>
<br />
<br />


$$y = \text{softmax}(Wx + b)$$

In [24]:
## Declaring our hypothesis funcion - use tf.nn.softmax() and tf.matmul() function to matrix multiply x and W.
## initialize to y


In [25]:
# establish the loss function and gradient descent optimizer operations
loss = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))
train_step = tf.train.GradientDescentOptimizer(.01).minimize(loss)

In [26]:
sess = tf.InteractiveSession()
tf.global_variables_initializer().run()

In [29]:
'''
Create a loop to run the training algorithm. The header has been defined for you already.
Inside the loop:
create variables batch_xs, and batch_ys, which will be our x training batch and y training batch. Use generate_bactch()
call sess.run() (info here: https://www.tensorflow.org/api_docs/python/tf/InteractiveSession#run)
    i) in sess.run(), the fetches argument will be the train_step defined above
   ii) The feed_dict will pass batch_xs for the x placeholder, and batch_ys for the y_ placeholder
'''

for i in range(50000):
    
    ##write code here:
       

In [30]:
'''
We want to see how accurate our predictions are compared to actual target values:
Use tf.equal() and tf.argmax() to compare y with y_1. 

'''
correct_prediction = 

accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32)) 


In [31]:
# test your predictions, using built in test dataset
print(sess.run(accuracy, feed_dict={x: test_x, y_: test_y}))

0.9209
